project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "P1_ratruns_analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Network procesing"
        menu:
          - A1_network.qmd
          - A2_graph.qmd
      - text: "Speed Data"
        menu:
          - B1_speed_data.qmd
          - B2_congestion_data.qmd
      - text: "Tickets of Traffic Offences"
        menu:
          - C1_infractions.qmd
      - text: "Tests"
        menu:
          - D1_graph_centrality_tests.qmd
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



