project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!ss/"
execute:
  warning: false
  error: false
  message: false
  freeze: auto
website:
  title: "P1_ratruns_analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Pre-processing"
        menu:
          - 1A_network.qmd
          - 1B_speed_data.qmd
          - 1C_infractions.qmd
      - text: "Centrality changes in Standard Network"
        menu:
          - 2A_Congested_graph_std_network.qmd
          - 2B_Analysis_std_network.qmd
      - text: "Centrality of WWD-enabled network"
        menu:
          - 3A_Congested_graph_WWD_allowed.qmd
          - 3B_Analysis_WWD_allowed.qmd
      - text: "Other data exploration"
        menu:
          - 4A_population.qmd
          - 4B_network.qmd
      - text: "Small Reproducible Test"
        menu:
          - D1_graph_centrality_tests.qmd
          - D2_congestion_tests.qmd
          - D3_WWD_joining.qmd
          - D3_Offences_joining.qmd
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



