---
editor: 
  markdown: 
    wrap: 72
---

# Congestion Data


```{r,message=FALSE}
#| label: libraries
#| message: false

options(repos = c(CRAN = "https://cloud.r-project.org"))
if (!require("remotes")) install.packages("remotes")
pkgs = c(
    "sf",
    "raster",
    "tidyverse",
    "googletraffic",
    "mapboxapi"
)

remotes::install_cran(pkgs)
sapply(pkgs, require, character.only = TRUE)
```


```{r}

```




## Google traffic

```{r}
#| label: read-sample-raster

## Make raster
r <- gt_make_raster(location   = c(4.702161, -74.093498),
                    height     = 2000,
                    width      = 2000,
                    zoom       = 16,
                    google_key = Sys.getenv("GMAPS"))

## Plot
r_df <- rasterToPoints(r, spatial = TRUE) |>  as.data.frame()
names(r_df) <- c("value", "x", "y")





ggplot() +
  geom_raster(data = r_df, 
  aes(x = x, y = y, 
  fill = as.factor(value))) +
  labs(fill = "Traffic\nLevel") +
  scale_fill_manual(values = c("green2", "orange", "red", "#660000")) +
  coord_quickmap() + 
  theme_void() +
  theme(plot.background = element_rect(fill = "white", color="white"))
```


```{r}
r1 <- raster::raster(ncol=10, nrow=10, xmn = -10, xmx = 1,  ymn = -10, ymx = 1)
r2 <- raster::raster(ncol=10, nrow=10, xmn = 0,   xmx = 10, ymn = 0,   ymx = 10)
r3 <- raster::raster(ncol=10, nrow=10, xmn = 9,   xmx = 20, ymn = 9,   ymx = 20)

r123 <- list(r1, r2, r3)

r <- gt_mosaic(r123)

plot(r)

```


## Mapbox



## Azure maps (formerly Bing Maps)